[project]
authors = [{ name = "Allen Chou", email = "f1470891079@gmail.com" }]
dependencies = ["diskcache", "numpy", "openai", "str_or_none", "tiktoken"]
description = "OpenAIEmbeddingsModel"
license = { text = "MIT" }
name = "openai-embeddings-model"
readme = "README.md"
requires-python = ">=3.11,<4"
version = "0.5.2"

[tool.poetry.group.dev.dependencies]
black = { extras = ["jupyter"], version = "*" }
faker = "*"
isort = "*"
mkdocs-material = "*"
poetry-plugin-export = "*"
pytest = "^8"
pytest-asyncio = "*"
pytest-env = "*"
setuptools = ">=69"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.isort]
profile = "black"

[tool.flake8]
ignore = ["E203", "E704", "W503"]
max-line-length = 88

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]
